apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: team-b-app
  name: team-b-app
  namespace: team-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team-b-app
  strategy: {}
  template:
    metadata:
      labels:
        app: team-b-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"   
    spec:
      containers:
        - image: nginx:1.28.0
          name: nginx
          ports:
            - containerPort: 80
            - containerPort: 9090
          resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
