apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: team-b-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-b-clusterrolebinding
  namespace: team-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: team-b-clusterrole
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: team-b
